# Generated by Django 5.2.6 on 2025-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, help_text="Optional city name, like 'Boracay' or 'Tokyo'", max_length=100, null=True),
        ),
    ]
