# Generated by Django 5.2.6 on 2025-10-03 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_destination_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='status',
            field=models.CharField(default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(),
        ),
    ]
